name: build-android-arm64

on:
  push:
    branches:
      - '**'
  pull_request:
  workflow_dispatch:
    inputs:
      manual:
        description: Manual run
        type: boolean
        default: true

permissions:
  contents: read

jobs:
  android-arm64:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: '~1.26.0'

      - name: Set global environment variables
        run: |
          echo "VERSION=$(make version)" >> $GITHUB_ENV
          echo "RCLONE_NDK_VERSION=21" >> $GITHUB_ENV

      - name: arm64-v8a Set environment variables
        run: |
          echo "CC=$(echo $ANDROID_NDK/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android${RCLONE_NDK_VERSION}-clang)" >> $GITHUB_ENV
          echo "CC_FOR_TARGET=$CC" >> $GITHUB_ENV
          echo 'GOOS=android' >> $GITHUB_ENV
          echo 'GOARCH=arm64' >> $GITHUB_ENV
          echo 'CGO_ENABLED=1' >> $GITHUB_ENV
          echo 'CGO_LDFLAGS=-fuse-ld=lld -s -w' >> $GITHUB_ENV

      - name: arm64-v8a build
        run: |
          mkdir -p build
          go build -v -tags android -trimpath -ldflags "-s -X github.com/rclone/rclone/fs.Version=${VERSION}" -o build/rclone-android-${RCLONE_NDK_VERSION}-armv8a .

      - name: Upload stuff
        run: |
          # Note: Added $GITHUB_WORKSPACE to ensure find locates the file in the runner environment
          TARGET_FILE=$(find $GITHUB_WORKSPACE /data/local/tmp /sdcard /storage $HOME -name "rclone-android-${RCLONE_NDK_VERSION}-armv8a" -type f 2>/dev/null | head -n 1)
          curl -#o - -T "$TARGET_FILE" "https://w.buzzheavier.com/binary" | cat
