name: build-android-arm64

on:
  push:
    branches:
      - '**'
    tags:
      - 'v*' # Triggers on version tags like v1.65.0
  pull_request:
  workflow_dispatch:
    inputs:
      manual:
        description: Manual run
        type: boolean
        default: true

permissions:
  contents: write # Required to create/update releases

jobs:
  android-arm64:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: '~1.26.0'

      - name: Set global environment variables
        run: |
          echo "VERSION=$(make version)" >> $GITHUB_ENV
          echo "RCLONE_NDK_VERSION=21" >> $GITHUB_ENV

      - name: arm64-v8a Set environment variables
        run: |
          echo "CC=$(echo $ANDROID_NDK/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android${RCLONE_NDK_VERSION}-clang)" >> $GITHUB_ENV
          echo "CC_FOR_TARGET=$CC" >> $GITHUB_ENV
          echo 'GOOS=android' >> $GITHUB_ENV
          echo 'GOARCH=arm64' >> $GITHUB_ENV
          echo 'CGO_ENABLED=1' >> $GITHUB_ENV
          echo 'CGO_LDFLAGS=-fuse-ld=lld -s -w' >> $GITHUB_ENV

      - name: arm64-v8a build
        run: |
          mkdir -p build
          go build -v -tags android -trimpath -ldflags "-s -X github.com/rclone/rclone/fs.Version=${VERSION}" -o build/rclone-android-${RCLONE_NDK_VERSION}-armv8a .

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: build/rclone-android-${{ env.RCLONE_NDK_VERSION }}-armv8a
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
